### ISSUE TITLE
have the option to combine nested or multiple sibling meta components

### ISSUE THREAD

**Issue by goldensunliu** [geekyme/react-doc-meta#4]
currently the most nested and youngest sibling meta component wins the meta war :-p and is chosen as the rendered meta tags. 
it would be nice to have the options to combine meta components' tags prop.

**Comment by geekyme** [comment]
I probably won't be doing this yet. I see the use case though, however i currently solve the problem by having a list of common meta tags array singleton that I import in pages that need them.
